// Used languages from https://stackoverflow.com/a/14302134
const languages = [
    {'code':'af','name':'Afrikaans'},
    {'code':'eu','name':'Basque'},
    {'code':'bg','name':'Bulgarian'},
    {'code':'ca','name':'Catalan'},
    {'code':'ar-EG','name':'Arabic (Egypt)'},
    {'code':'ar-JO','name':'Arabic (Jordan)'},
    {'code':'ar-KW','name':'Arabic (Kuwait)'},
    {'code':'ar-LB','name':'Arabic (Lebanon)'},
    {'code':'ar-QA','name':'Arabic (Qatar)'},
    {'code':'ar-AE','name':'Arabic (UAE)'},
    {'code':'ar-MA','name':'Arabic (Morocco)'},
    {'code':'ar-IQ','name':'Arabic (Iraq)'},
    {'code':'ar-DZ','name':'Arabic (Algeria)'},
    {'code':'ar-BH','name':'Arabic (Bahrain)'},
    {'code':'ar-LY','name':'Arabic (Libya)'},
    {'code':'ar-OM','name':'Arabic (Oman)'},
    {'code':'ar-SA','name':'Arabic (Saudi Arabia)'},
    {'code':'ar-TN','name':'Arabic (Tunisia)'},
    {'code':'ar-YE','name':'Arabic (Yemen)'},
    {'code':'cs','name':'Czech'},
    {'code':'nl-NL','name':'Dutch (Netherlands)'},
    {'code':'en-AU','name':'English (Australia)'},
    {'code':'en-CA','name':'English (Canada)'},
    {'code':'en-IN','name':'English (India)'},
    {'code':'en-NZ','name':'English (New Zealand)'},
    {'code':'en-ZA','name':'English (South Africa)'},
    {'code':'en-GB','name':'English (UK)'},
    {'code':'en-US','name':'English (US)'},
    {'code':'fi','name':'Finnish'},
    {'code':'fr-FR','name':'French (France)'},
    {'code':'gl','name':'Galician'},
    {'code':'de-DE','name':'German (Germany)'},
    {'code':'he','name':'Hebrew'},
    {'code':'hu','name':'Hungarian'},
    {'code':'is','name':'Icelandic'},
    {'code':'it-IT','name':'Italian (Italy)'},
    {'code':'id','name':'Indonesian'},
    {'code':'ja','name':'Japanese'},
    {'code':'ko','name':'Korean'},
    {'code':'la','name':'Latin'},
    {'code':'zh-CN','name':'Mandarin Chinese (Simplified, China)'},
    {'code':'zh-TW','name':'Mandarin Chinese (Traditional, Taiwan)'},
    {'code':'zh-HK','name':'Mandarin Chinese (Simplified, Hong Kong)'},
    {'code':'zh-yue','name':'Yue Chinese (Traditional, Hong Kong)'},
    {'code':'ms-MY','name':'Malaysian (Malaysia)'},
    {'code':'no-NO','name':'Norwegian (Norway)'},
    {'code':'pl','name':'Polish'},
    {'code':'pt-PT','name':'Portuguese (Portugal)'},
    {'code':'pt-BR','name':'Portuguese (Brazil)'},
    {'code':'ro-RO','name':'Romanian (Romania)'},
    {'code':'ru','name':'Russian'},
    {'code':'sr-SP','name':'Serbian (Serbia)'},
    {'code':'sk','name':'Slovak'},
    {'code':'es-AR','name':'Spanish (Argentina)'},
    {'code':'es-BO','name':'Spanish (Bolivia)'},
    {'code':'es-CL','name':'Spanish (Chile)'},
    {'code':'es-CO','name':'Spanish (Colombia)'},
    {'code':'es-CR','name':'Spanish (Costa Rica)'},
    {'code':'es-DO','name':'Spanish (Dominican Republic)'},
    {'code':'es-EC','name':'Spanish (Ecuador)'},
    {'code':'es-SV','name':'Spanish (El Salvador)'},
    {'code':'es-GT','name':'Spanish (Guatemala)'},
    {'code':'es-HN','name':'Spanish (Honduras)'},
    {'code':'es-MX','name':'Spanish (Mexico)'},
    {'code':'es-NI','name':'Spanish (Nicaragua)'},
    {'code':'es-PA','name':'Spanish (Panama)'},
    {'code':'es-PY','name':'Spanish (Paraguay)'},
    {'code':'es-PE','name':'Spanish (Peru)'},
    {'code':'es-PR','name':'Spanish (Puerto Rico)'},
    {'code':'es-ES','name':'Spanish (Spain)'},
    {'code':'es-US','name':'Spanish (US)'},
    {'code':'es-UY','name':'Spanish (Uruguay)'},
    {'code':'es-VE','name':'Spanish (Venezuela)'},
    {'code':'sv-SE','name':'Swedish (Sweden)'},
    {'code':'tr','name':'Turkish'},
    {'code':'zu','name':'Zulu'}
  ];

function getLocaleFromHtmlLang(htmlLang: string) {
    const langMap: Record<string, string> = {
        'ar': 'ar-SA',
        'en': 'en-US',
        'fr': 'fr-FR',
        'de': 'de-DE',
        'it': 'it-IT',
        'es': 'es-ES',
        'pt': 'pt-PT',
        'zh': 'zh-CN',
        'nl': 'nl-NL',
        'sv': 'sv-SE',
        'ms': 'ms-MY',
        'no': 'no-NO',
        'sr': 'sr-SP',
    };

    return langMap[htmlLang] || htmlLang;
};

export {getLocaleFromHtmlLang, languages};